name: Check

on: [push, pull_request]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        tox-filter:
          - "py3.8"
          - "py3.9"
          - "py3.10"
          - "py3.11"
          - "py3.12"
          - "py3.13"
    name: run checks ${{ matrix.tox-filter }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build and pull images
        run: |
          docker compose build
          docker compose pull --quiet
      - name: run checks
        run: docker compose run --rm django-pg-zero-downtime-migrations-tests tox -f ${{ matrix.tox-filter }}
