name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/django-pg-zero-downtime-migrations:latest

  check:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        tox-filter:
          - "py3.8"
          - "py3.9"
          - "py3.10"
          - "py3.11"
          - "py3.12"
          - "py3.13"
    name: run checks ${{ matrix.tox-filter }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: pull images
        run: docker compose pull --quiet
      - name: run checks
        run: docker compose run --rm django-pg-zero-downtime-migrations-tests tox -f ${{ matrix.tox-filter }}
