name: Check

on: [push, pull_request]

jobs:
  check:
    name: run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build
        run: docker compose build
      - name: pull
        run: docker compose pull --quiet
      - name: run checks
        run: docker compose run --rm django-pg-zero-downtime-migrations-tests tox
