name: Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: django-pg-zero-downtime-migrations:latest
          outputs: type=docker,dest=${{ runner.temp }}/main-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-image
          path: ${{ runner.temp }}/main-image.tar

  check:
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        tox-filter:
          - "py3.8"
          - "py3.9"
          - "py3.10"
          - "py3.11"
          - "py3.12"
          - "py3.13"
    name: run checks ${{ matrix.tox-filter }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: main-image
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/main-image.tar
          docker image ls -a

      - name: Pull DB images
        run: docker compose pull --quiet

      - name: run checks
        run: docker compose run --rm django-pg-zero-downtime-migrations-tests tox -f ${{ matrix.tox-filter }}
